#!/usr/bin/env node
/**
 * TuPhim Distribution — Setup Script
 * Run once to generate admin password hash and .env file
 *
 * Usage: node setup.js
 */

const bcrypt = require('bcryptjs');
const crypto = require('crypto');
const readline = require('readline');
const fs = require('fs');
const path = require('path');

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
const q = (prompt) => new Promise(res => rl.question(prompt, res));

async function main() {
    console.log('\n🎬 TuPhim Distribution — First Time Setup\n');
    console.log('Tạo file .env với thông tin bảo mật của bạn.\n');

    const username = await q('Admin username [tuphim_admin]: ') || 'tuphim_admin';
    const password = await q('Admin password: ');
    if (!password) { console.error('❌ Mật khẩu không được để trống!'); process.exit(1); }

    console.log('\n🔐 Đang tạo bcrypt hash (có thể mất vài giây)…');
    const hash = await bcrypt.hash(password, 12);
    const secret = crypto.randomBytes(64).toString('hex');

    const adminPath = await q('Secret admin URL path [qltv-tp8x2024]: ') || 'qltv-tp8x2024';
    const domain = await q('Domain [https://tuphim.online]: ') || 'https://tuphim.online';

    rl.close();

    const envContent = `# TuPhim Distribution — Environment Config
# Generated by setup.js on ${new Date().toISOString()}

PORT=3001
NODE_ENV=production

APP_DOMAIN=${domain}
ADMIN_SECRET_PATH=${adminPath}

JWT_SECRET=${secret}
JWT_EXPIRES_IN=8h

ADMIN_USERNAME=${username}
ADMIN_PASSWORD_HASH=${hash}

# IPA Signing — cert_legacy.p12, password: 1
CERT_PATH=../certificate/cert_legacy.p12
CERT_PASSWORD=1
PROVISION_PATH=../certificate/cert.mobileprovision

APP_NAME=TuPhim
BUNDLE_ID=com.tophim.app
APP_VERSION=2.1.0

STORAGE_PATH=./storage
MAX_UPLOAD_MB=500
`;

    const envPath = path.join(__dirname, '..', 'server', '.env');
    fs.writeFileSync(envPath, envContent, 'utf-8');

    console.log(`\n✅ File .env đã được tạo tại: ${envPath}`);
    console.log('\n📋 Thông tin đăng nhập admin:');
    console.log(`   URL:      ${domain}/${adminPath}/login.html`);
    console.log(`   Username: ${username}`);
    console.log(`   Password: ${password}`);
    console.log('\n⚠️  Không chia sẻ file .env với ai!');
    console.log('\n🚀 Bước tiếp theo: cd server && npm install && node server.js\n');
}

main().catch(e => { console.error(e); process.exit(1); });
